ECMPS beta examples
USEPA/cam-api-examples pull request #10
Opened 2023-10-23 17:24 UTC by kstetsyuk

2023-11-01 18:51 UTC, j-tafoya commented on .github/workflows/jekyll-gh-pages.yml
> +          node-version: 16
May want to increase this version, since node 16 has reached EOL.

2023-11-27 19:52 UTC, j-tafoya requested changes
This looks good! See my comments in the files for more feedback. I think the only thing to change may be the node version. I really like the format of the tables and the light dependencies!

2023-11-27 21:14 UTC, kstetsyuk commented
I agree on trying to not duplicate code. I'm sure there's something out there we could use to remediate. Other than that, changes are made! @j-tafoya

2023-11-27 21:44 UTC, j-tafoya approved these changes
👍

2023-11-27 21:49 UTC, merged