Improve bulk data example and notes
USEPA/cam-api-examples pull request #7
Opened 2023-04-03 14:42 UTC by kstetsyuk

2023-04-17 19:30 UTC, j-tafoya requested changes
Just a few minor changes needed, some of which are "nice-to-haves" so feel free to ignore those

2023-04-17 19:30 UTC, j-tafoya commented on Python/facility_data_demo.py
> +if len(parameters['year']) > 4:
This isn't parsing the 2020|2021 as a list, but instead counting the length of the string. You may want to check this another way.

2023-04-17 19:30 UTC, j-tafoya commented on R/account_data_demo.R
Need `library(dplyr)`

2023-04-18 11:36 UTC, kstetsyuk commented
@j-tafoya I will get on these - they all sound good to me. Thank you for suggestions and extra eyes!!

2023-05-24 18:31 UTC, kstetsyuk commented
@j-tafoya Can you take a look at this when you can? Thanks!

2023-06-01 14:37 UTC, j-tafoya reviewed
Looks good! Just a couple of package imports needed and it's good to go! Thanks for all your great work on this! This will be super helpful for users!

2023-06-06 13:09 UTC, j-tafoya approved these changes
Perfect! Thanks!

2023-06-06 13:11 UTC, merged